"""add patient notes table

Revision ID: 58668e3c3d3c
Revises: bb0b355531ba
Create Date: 2026-03-05 21:58:32.385687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58668e3c3d3c'
down_revision: Union[str, Sequence[str], None] = 'bb0b355531ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_notes_id'), 'patient_notes', ['id'], unique=False)
    op.create_index(op.f('ix_patient_notes_patient_id'), 'patient_notes', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_notes_patient_id'), table_name='patient_notes')
    op.drop_index(op.f('ix_patient_notes_id'), table_name='patient_notes')
    op.drop_table('patient_notes')
    # ### end Alembic commands ###
